packages:
  - "apps/*"
  - "packages/*"

onlyBuiltDependencies:
  - better-sqlite3
  - core-js
  - cpu-features
  - esbuild
  - ssh2
  - "@fortawesome/fontawesome-common-types"
  - "@fortawesome/fontawesome-svg-core"
  - "@fortawesome/free-regular-svg-icons"
  - "@fortawesome/free-solid-svg-icons"
