#!/bin/bash
echo ""
echo ">>>> Build in PowerShell (not WSL) to avoid rollup issues"
powershell.exe -Command "cd C:\Users\mark\apps\tv-series-client; npm run build-vite"

echo ""
echo ">>>> Deploy client"
rsync -av --delete \
      -e "ssh -i $HOME/.ssh/id_rsa -o IdentitiesOnly=yes" \
      /mnt/c/Users/mark/apps/tv-series-client/shows/       \
      root@hahnca.com:/root/dev/apps/tv-series-client/shows

echo ""
echo ">>>> Deploy torrents server"
rsync -av --delete \
      --exclude 'node_modules' \
      -e "ssh -i $HOME/.ssh/id_rsa -o IdentitiesOnly=yes" \
      /mnt/c/Users/mark/apps/tv-series-client/torrents/    \
      root@hahnca.com:/root/dev/apps/tv-series-client/torrents


echo ""
echo ">>>> Run torrents release steps on remote server"
ssh -i $HOME/.ssh/id_rsa -o IdentitiesOnly=yes root@hahnca.com \
      'bash -lc "export NVM_DIR=\"\$HOME/.nvm\"; [ -s \"\$NVM_DIR/nvm.sh\" ] && . \"\$NVM_DIR/nvm.sh\"; nvm use --lts >/dev/null 2>&1 || true; cd /root/dev/apps/tv-series-client/torrents; npm install; pm2 restart torrents-server || pm2 start src/server.js --name torrents-server"'

